parameters:
#    reverse_auction_webservices.example.class: ReverseAuction\WebservicesBundle\Example

services:
#    reverse_auction_webservices.example:
#        class: %reverse_auction_webservices.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
