winnerinfo:
    path:     /
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:index" }

winnerinfo_show:
    path:     /{id}/show
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:show" }

winnerinfo_new:
    path:     /new
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:new" }

winnerinfo_create:
    path:     /create
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:create" }
    requirements: { _method: post }

winnerinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:edit" }

winnerinfo_update:
    path:     /{id}/update
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:update" }
    requirements: { _method: post|put }

winnerinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReverseAuctionReverseAuctionBundle:WinnerInfo:delete" }
    requirements: { _method: post|delete }
